name: 百聆（bailing） 
version: 1.0

logging:
  level: debug

# 唤醒词
WakeWord: 百聆

interrupt: false
# 是否开启工具调用
StartTaskMode: true
# 具体处理时选择的模块
selected_module:
  Recorder: RecorderPyAudio
  ASR: FunASR
  VAD: SileroVAD
  LLM: OpenAILLM
  TTS: EdgeTTS
  Player: PygameSoundPlayer

Recorder:
  RecorderPyAudio:
    output_file: tmp/recorder_output/

ASR:
  FunASR:
    model_dir: FunAudioLLM/SenseVoiceSmall
    output_file: tmp/asr_output/

VAD:
  SileroVAD:
    sampling_rate: 16000
    threshold: 0.5
    min_silence_duration_ms: 200  # 如果说话停顿比较长，可以把这个值设置大一些

LLM:
  OpenAILLM:
    model_name: deepseek-chat
    url: https://api.deepseek.com
    api_key: sk-e4ad7f13f96747c38168a0cd8ec346f2

TTS:
  MacTTS:
    voice: Tingting
    output_file: tmp/tts_output/
  EdgeTTS:
    voice: zh-CN-XiaoxiaoNeural
    output_file: tmp/tts_output/
  GTTS:
    lang: zh
    output_file: tmp/tts_output/
  CosyvoiceTTS:
    output_file: tmp/tts_output/
  CHATTTS:
    output_file: tmp/tts_output/
  KOKOROTTS:
    output_file: tmp/tts_output/
    lang: z
    voice: zm_yunyang

Player:
  PygameSoundPlayer: null
  PygamePlayer: null
  CmdPlayer: null
  PyaudioPlayer: null

Rag:
  doc_path: documents/
  emb_model: BAAI/bge-small-zh-v1.5
  model_name: deepseek-chat
  url: https://api.deepseek.com
  api_key: sk-e4ad7f13f96747c38168a0cd8ec346f2

Memory:
  dialogue_history_path: tmp/
  memory_file: tmp/memory.json
  model_name: deepseek-chat
  url: https://api.deepseek.com
  api_key: sk-e4ad7f13f96747c38168a0cd8ec346f2

TaskManager:
  functions_call_name: plugins/function_calls_config.json
  aigc_manus_enabled: false





